In [1]:
import numpy as np

In [3]:
v1 = np.array([10, 20, 5])
v2 = np.array([5, 5, 10])
print(v1)
print(v2)

[10 20  5]
[ 5  5 10]


In [4]:
print(v1+v2)
print(v1-v2)
print(v1*v2)
print(v1*2)

[15 25 15]
[ 5 15 -5]
[ 50 100  50]
[20 40 10]


In [5]:
print(v1.dot(v2))

200


In [9]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

m2 = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])

In [10]:
print(m1)
print("---------------")
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
print(m1+m2)
print("---------------")
print(m1-m2)
print("---------------")
print(m1*m2)
print("---------------")
print(m1*2)
print("---------------")

[[11 22 33]
 [44 55 66]
 [77 88 99]]
---------------
[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]
---------------
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
---------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
---------------


In [13]:
print(m1.dot(m2))

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [27]:
print(v1.ndim)
print(v1.shape)
print(m1.ndim)
print(m1.shape)

1
(3,)
2
(3, 3)


In [23]:
class student:
    def __init__(self, name):
        self.name = name
    @property # make method a property
    def get_info(self):
        return f"my name is {self.name}"

In [24]:
s1 = student("Ahmed")
s1.get_info()

TypeError: 'str' object is not callable

In [25]:
s1.get_info

'my name is Ahmed'

In [28]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape(3, 2)

In [29]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
vec = np.array([1, 2, 3, 4])   
vec.shape[0]


4

In [34]:
mat = vec.reshape(vec.shape[0],1) 
mat.shape

(4, 1)

In [37]:
vec = np.array([1, 2, 3, 4])   
mat = vec[:None]
mat.shape

(4,)

In [39]:
mat = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
mat.dtype

dtype('int64')

In [45]:
mat = np.array([["5", 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
mat.dtype

dtype('<U21')

In [46]:
mat

array([['5', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [47]:
f_mat = mat.astype(float)
f_mat

array([[5., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])